### PR TITLE
Escape reserved name/keyword identifiers

### PR DESCRIPTION
**Pull request by drvink**

### CODE REVIEW

**Comment by dsyme** [comment]
Plus plus double good. Adding tests would be nice too

**Comment by drvink** [comment]
I agree, though right now there are exactly zero tests (despite someone's best intentions, given the empty test project :)), and I don't have enough spare cycles to figure out how to add test goop to the project. Since folks are waiting on the bug to be fixed, is it OK to merge this now and think about adding tests later?

**Comment by dsyme** [comment]
Yes, it's ok to merge this

https://github.com/fsprojects/FSharp.Compiler.CodeDom/tree/master/tests/codedom is a pretty solid set of tests for some of the functionality.  Though I agree it's not covering CleanCodeDomGenerator.

**Comment by drvink** [comment]
Oh, I completely missed that was even there. I just saw the tests visible within the VS project and assumed that was all there was!

**Comment by dsyme** [comment]
That's the official codedom test suite from way back in 2005 or so.  Not all of it passes but between @tpetricek and I we got most of it to pass.

**Pull request merged**
