### PR TITLE
followup changes from #6

### PR DESCRIPTION
**Pull request by drvink**
* style fixes
* assembly installer is now signed
* MSI installer now properly elevates privileges when making changes to machine.config
* provider now also registers handling of .fsx and .fsscript

### CODE REVIEW

**Comment by drvink** [comment]
@dsyme This fixes some issues in the previous PR and makes the changes you'd asked for, and also takes care of issue #3 (or at least will take care of it next time a NuGet package is released).

**Comment by dsyme** [comment]
OK, great, go ahead and merge!

**Comment by drvink** [comment]
I would, but either I'm doing something wrong or I don't have permission. :) (It says "This pull request can be automatically merged by project collaborators. Only those with write access to this repository can merge pull requests.")

**Comment by dsyme** [comment]
That should be fixed now

**Pull request merged**
