### PR TITLE
Update Mono version

### PR DESCRIPTION
**Pull request by sergey-tihon**
for #16

### CODE REVIEW

**Comment by dsyme** [comment]
Nice

**Comment by sergey-tihon** [comment]
I like that everything here was done from the browser, without local code checkout )

**Comment by drvink** [comment]
Do we have an official (i.e. fsprojects) appveyor to use instead? If not, this looks fine to me.

**Comment by sergey-tihon** [comment]
We have ` fsprojects` account, but I do not have access to it.
Current(my) appveyor setup in fully integrated with this repo (with webhooks) so it should be OK

**Comment by drvink** [comment]
Sounds fine for now. Thanks for fixing this--I knew the build was working but I didn't have time to look into how to make the CI stuff happy.

**Pull request merged**
